# Generated by Django 5.0.6 on 2024-06-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
